In [10]:
from urllib.request import urlopen
from bs4 import BeautifulSoup
from urllib.request import urlopen
from urllib.error   import HTTPError
from urllib.error   import URLError

In [194]:
from selenium import webdriver
import time
path = './driver/chromedriver.exe'
driver = webdriver.Chrome(path)

In [303]:
import pandas as pd

In [318]:
date = pd.read_excel('korean.xlsx',header=None)
date_list = [ i for i in date.iloc[:,0]]

[20130103, 20130110, 20130117, 20130124, 20130131, 20130207, 20130214, 20130221, 20130228, 20130307, 20130314, 20130321, 20130328, 20130404, 20130411, 20130418, 20130425, 20130502, 20130509, 20130516, 20130523, 20130530, 20130606, 20130613, 20130620, 20130704, 20130711, 20130718, 20130725, 20130801, 20130808, 20130815, 20130822, 20130829, 20130905, 20130912, 20130919, 20130926, 20131003, 20131010, 20131017, 20131024, 20131031, 20131107, 20131114, 20131121, 20131128, 20131205, 20131212, 20131219, 20131226, 20140102, 20140109, 20140116, 20140123, 20140130, 20140206, 20140213, 20140220, 20140227, 20140306, 20140313, 20140320, 20140327, 20140403, 20140410, 20140501, 20140508, 20140515, 20140522, 20140529, 20140605, 20140612, 20140619, 20140626, 20140710, 20140717, 20140724, 20140731, 20140807, 20140814, 20140821, 20140828, 20140904, 20140911, 20140918, 20141009, 20141016, 20141023, 20141030, 20141106, 20141113, 20141120, 20141127, 20141204, 20141211, 20141218, 20141225, 20150108, 20150115, 20150122, 20150129, 20150205, 20150212, 20150219, 20150226, 20150305, 20150312, 20150319, 20150326, 20150402, 20150409, 20150416, 20150423, 20150430, 20150507, 20150514, 20150521, 20150528, 20150604, 20150611, 20150618, 20150625, 20150702, 20150709, 20150716, 20150723, 20150730, 20150806, 20150813, 20150820, 20150827, 20150910, 20150917, 20150924, 20151001, 20151008, 20151015, 20151022, 20151029, 20151105, 20151112, 20151119, 20151126, 20151203, 20151210, 20151217, 20151224, 20151231, 20160107, 20160114, 20160121, 20160128, 20160204, 20160211, 20160218, 20160225, 20160303, 20160310, 20160317, 20160324, 20160331, 20160407, 20160414, 20160421, 20160428, 20160505, 20160512, 20160519, 20160526, 20160602, 20160609, 20160616, 20160623, 20160630, 20160707, 20160714, 20160721, 20160728, 20160804, 20160818, 20160825, 20160901, 20160908, 20160915, 20160922, 20160929, 20161006, 20161013, 20161020, 20161027, 20161103, 20161110, 20161117, 20161124, 20161201, 20161208, 20161215, 20161222, 20161229, 20170105, 20170112, 20170119, 20170126, 20170202, 20170216, 20170223, 20170302, 20170309, 20170316, 20170323, 20170406, 20170413, 20170420, 20170427, 20170504, 20170511, 20170518, 20170525, 20170601, 20170608, 20170615, 20170622, 20170629, 20170713, 20170720, 20170803, 20170810, 20170817, 20170824, 20170831, 20170907, 20170914, 20170921, 20170928, 20171005, 20171012, 20171019, 20171026, 20171102, 20171109, 20171116, 20171123, 20171130, 20171207, 20171214, 20171228, 20180104, 20180111, 20180118, 20180125, 20180201, 20180208, 20180215, 20180222, 20180301, 20180308, 20180315, 20180322, 20180329, 20180412, 20180419, 20180426, 20180503, 20180510, 20180517, 20180524, 20180531, 20180607, 20180614, 20180621, 20180628, 20180705, 20180712, 20180719, 20180726, 20180802, 20180809, 20180816, 20180823, 20180906, 20180913, 20180927, 20181004, 20181011, 20181018, 20181025, 20181101, 20181108, 20181115, 20181122, 20181129, 20181206, 20181213, 20181220, 20181227, 20190103, 20190110, 20190117, 20190124, 20190131, 20190207, 20190214, 20190221, 20190307, 20190314, 20190321, 20190328, 20190404, 20190418, 20190425, 20190502, 20190509, 20190516, 20190523, 20190606, 20190613, 20190620, 20190627, 20190704, 20190711, 20190718, 20190725, 20190815, 20190822, 20190829, 20190905, 20190912, 20190919, 20190926, 20191010, 20191017, 20191024, 20191031, 20191107, 20191114, 20191121, 20191128, 20191205, 20191212, 20191219, 20191226, 20200102, 20200109, 20200116, 20200123, 20200130, 20200206, 20200213, 20200220, 20200312, 20200319, 20200326, 20200402, 20200409, 20200416, 20200423, 20200430, 20200507, 20200514, 20200521, 20200528, 20200604, 20200611, 20200618, 20200625, 20200702, 20200709, 20200716, 20200723, 20200730, 20200806, 20200813, 20200820, 20200827, 20200910, 20200917, 20200924, 20201001, 20201008, 20201015, 20201022, 20201029, 20201105, 20201112, 20201119, 20201126]

In [309]:
def rate_crr(data_list):
    result_rate_list = []
    result_date_list = []
    for date in date_list:
        driver.get('https://www.nielsenkorea.co.kr/tv_terrestrial_day.asp?menu=Tit_1&sub_menu=1_1&area=00&begin_date='+str(date))
        page = driver.find_elements_by_css_selector('.ranking_tb')
        page_tr = page[0].find_elements_by_tag_name('tr')
        name_list = []
        rate_list = []
        for tr in page_tr:
            page_td = tr.find_elements_by_tag_name('td')
            for idx,td_text in enumerate(page_td):
                if len(name_list) == 0:
                    if td_text.text == '한국인의밥상':
                        name_list.append(td_text.text)
                else:
                    if len(rate_list) == 0:
                        rate_list.append(td_text.text)
                        result_date_list.append(date)
                        result_rate_list.append(td_text.text)
                        break  

                        
    return  result_rate_list,  result_date_list

In [319]:
result_rate_list,  result_date_list = rate_crr(date_list)

In [322]:
print(result_rate_list[:10])
print(result_date_list[:10])

['15.2', '16.5', '14.4', '14.8', '13.5', '13.0', '12.6', '12.4', '12.1', '13.6']
[20130103, 20130110, 20130117, 20130124, 20130131, 20130207, 20130214, 20130221, 20130228, 20130307]

In [324]:
rate_csv = pd.DataFrame({
    'date' : result_date_list,
     'ratio'  : result_rate_list
                        })
rate_csv

         date ratio
0    20130103  15.2
1    20130110  16.5
2    20130117  14.4
3    20130124  14.8
4    20130131  13.5
5    20130207  13.0
6    20130214  12.6
7    20130221  12.4
8    20130228  12.1
9    20130307  13.6
10   20130314  12.1
11   20130321  11.9
12   20130328  12.7
13   20130404  10.8
14   20130411  11.7
15   20130418  12.8
16   20130425  11.7
17   20130502  10.1
18   20130509  10.1
19   20130516   8.7
20   20130523   9.7
21   20130530   7.7
22   20130606  10.7
23   20130613   9.9
24   20130620   9.1
25   20130704  13.1
26   20130711  12.8
27   20130718  10.2
28   20130725   9.5
29   20130801  10.8
..        ...   ...
354  20200430   8.1
355  20200507   7.0
356  20200514   6.9
357  20200521   7.4
358  20200528   7.2
359  20200604   7.0
360  20200611   6.5
361  20200618   6.8
362  20200625   8.1
363  20200702   7.2
364  20200709   7.2
365  20200716   7.3
366  20200723   8.6
367  20200730   7.2
368  20200806   7.5
369  20200813   7.1
370  20200820   7.5
371  20200827   8.2
372  20200910   9.4
373  20200917   8.7
374  20200924   8.5
375  20201001   7.4
376  20201008  10.1
377  20201015   8.0
378  20201022   8.0
379  20201029   8.1
380  20201105  10.4
381  20201112   7.9
382  20201119   8.6
383  20201126   8.9

[384 rows x 2 columns]

In [325]:
rate_csv.to_csv('./data/rate_csv.csv',mode='w',encoding='utf-8',index=False)

In [320]:
print(len(result_rate_list))
print(len(result_date_list))

384
384